# Generated by Django 3.2.8 on 2021-11-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_auto_20211126_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='visibiliry',
            field=models.TextField(choices=[('public', 'public'), ('private', 'private'), ('some people', 'some people')], default='public'),
        ),
    ]
